### ISSUE TITLE
Module still alive?

### ISSUE THREAD

**Issue by jyaworski** [CERIT-SC/puppet-yum#14]
Hi @vholer and @arax. Is this module still alive? If it's fallen into a state where it can no longer be maintained (via time or some other constraint), can you give the repository to someone else? For example, we at [VoxPupuli](https://github.com/voxpupuli) would be happy to take ownership.

**Comment by vholer** [comment]
Hi @jyaworski. Yes, the module is still alive, but my capacity is now very limited. If you think it needs more improvements, I can apply all the pull requests, release new version on Puppet Forge and hand over future development to @VoxPopuli. You can then fork it into your GH organization and the commit track will be preserved.

**Comment by jyaworski** [comment]
@vholer that sounds good. When you're ready, add a deprecation notice to the README and push a forge release pointing to the VP version. Ping us and we'll fork it and handle it from there.

**Comment by vholer** [comment]
Hi @jyaworski, I have merged and fixed pending PRs and released updated module on PF. Please give me one more week to check for any issues. Then I'll let you know once again. Thanks.

**Comment by joshuabaird** [comment]
@vholer, the deprecation notice links to a missing module on Forge.  Is this expected?

**Comment by vholer** [comment]
@joshuabaird: Yes, it is (or at least I thought it'll be future location of this module).
@jyaworski: I haven't noticed any problems so far, you can fork the module into your VoxPopuli GitHub organization and use as you think. Please leave references on CERIT-SC, in readme, license... somewhere you think it's good and enough. I'll from time to time contribute to your new module, but GitHub PR workflow is fine for me.

**Comment by kallies** [comment]
The link [1] to new module doesn't work. It responds with "HTTP/1.1 404 Not Found".

[1] https://forge.puppet.com/puppet/yum

**Comment by wortmanb** [comment]
I also would love to lay my hands on this, but it appears to be caught between deprecation and re-release.

**Comment by vholer** [comment]
@jyaworski Please can you fork the module into VoxPopuli and release first version so that the deprecation message is valid and people aren't confused. Otherwise I'll remove the message by the end of June and continue with support on same best-effort level, as I did. Thanks.

**Comment by jyaworski** [comment]
I just forked it. Give me until the end of the week. It will probably be done today, though. There are a few things we need to do before we release.

**Comment by vholer** [comment]
Hi @jyaworski , can you please relase the module on PF so that people are not confused? I think there doesn't have to be much changes for initial release... Anything for start is better than nothing. Thanks a lot <3

**Comment by vholer** [comment]
I can see the module has been released, closing issue. Thanks!
