### ISSUE TITLE
Yum group presence check broken in RHEL7

### ISSUE THREAD

**Issue by djroomb4** [CERIT-SC/puppet-yum#7]
In RHEL7, the output of yum grouplist <group> displays 'Installed environment groups:' or 'Installed groups:', instead of 'Installed Groups:'. Using a case insensitive search with egrep should fix for RHEL7.

**Comment by vholer** [comment]
Thank you for your report. Issue should be fixed and new module version 0.9.6 has been released on Puppet Forge.
