### ISSUE TITLE
Stdlib version requirement

### ISSUE THREAD

**Issue by electrical** [CERIT-SC/puppet-yum#8]
Hi,

Is there a specific reason why you are limiting the usage of stdlib to 4.0 or higher?
I would love to discuss if we could lower this requirement so it can work with older versions of PE.

Thanks!

**Comment by mmckinst** [comment]
it uses the delete_undef_values function in init.pp . that function was only added in stdlib 4.2.0: https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/CHANGELOG.md#2014-05-08---release---420

older verions of this module will probably work fine with an older version of stdlib

**Comment by electrical** [comment]
Ahh okay, makes sense then, no problem :-)
